### ISSUE TITLE
Error freeing handle for connection

### ISSUE THREAD

**Issue by GoD-Tony** [asherkin/webcon#4] opened 2015-05-11 16:44 UTC
Getting this in my error log when shutting down the server (windows/csgo). Made sure that my local changes were removed to confirm.

```
L 05/11/2015 - 18:36:01: SourceMod error session started
L 05/11/2015 - 18:36:01: Info (map "de_dust") (file "errors_20150511.log")
L 05/11/2015 - 18:36:01: [WEBCON] Error freeing handle for connection. (230022, 3)
L 05/11/2015 - 18:36:01: [WEBCON] Error freeing handle for connection. (260023, 3)
L 05/11/2015 - 18:36:01: [WEBCON] Error freeing handle for connection. (2f0021, 3)
L 05/11/2015 - 18:36:01: Error log file session closed.
```

**Comment by asherkin** [comment] 2015-05-11 16:49
It is caused by SM closing all handles before SDK_OnUnload is called. I can't really see any sane way to avoid the errors correctly, and I think the answer is to just check if the result == 3 (Already Freed) and ignore the error.

**Closed as completed** 2015-05-12 19:12 UTC
